name: run conditional BLE feature compilation
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 6'
jobs:
  run-conditional-feature-compilation-test:
    name: Conditional BLE features compilation tested
    runs-on: ubuntu-latest
    container: mbedos/mbed-os-env:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd BLE_SupportedFeatures
          mbed deploy
          for f in ../resources/test_configs/*; do
            echo "Configuration file ${f}: "
            echo "-------------------------------------------------------------------------"
            cat "${f}"
            echo "-------------------------------------------------------------------------"
            mbed compile -t GCC_ARM -m NRF52840_DK --app-config "${f}"
          done
